server:
  port: 8080
spring:
  application:
     name: api-gateway
  cloud:
   gateway:
       routes:
       - id: student
         uri: lb://STUDENT
         predicates:
           - Path=/api/v1/students/**
       - id: course
         uri: lb://COURSE
         predicates:
           - Path=/api/v1/courses/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
management:
  tracing:
    sampling:
      probability: 1.0