server:
  port: 8082
spring:
  application:
     name: Course
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/course
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      default-zone: eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
management:
  tracing:
    sampling:
      probability: 1.0